In [5]:
import pandas as pd
df=pd.read_csv('sentiment_cleaned.csv')

In [6]:
df.head()

,sentiment_numeric,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,...,fear,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy
0,1,24,9,116,1,0.0,0.0,0.0,1.0,19,...,0.0,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333
1,0,12,5,53,0,0.0,0.0,0.0,1.0,23,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
2,0,12,7,54,1,0.0,0.0,0.0,1.0,16,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
3,0,9,3,40,1,0.0,0.0,0.0,1.0,22,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
4,-1,15,6,85,4,0.0,0.0,0.0,1.0,12,...,0.0,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000

In [7]:
df.isnull().sum()

sentiment_numeric        0
word_count               0
num_stop_words           0
num_chars                0
num_punctuation_chars    0
category_gaming          0
category_movies          0
category_music           0
category_technology      0
hour                     0
weekday                  0
month                    0
fear                     0
anger                    0
anticipation             0
trust                    0
surprise                 0
positive                 0
negative                 0
sadness                  0
disgust                  0
joy                      0
dtype: int64

In [8]:
df.shape

(49477, 22)

In [9]:
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
# setup mlflow tracking server

mlflow.set_tracking_uri("http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/")

In [14]:
# Set or create an experiment
mlflow.set_experiment("RF Baseline")

2025/11/22 14:09:28 INFO mlflow.tracking.fluent: Experiment with name 'RF Baseline' does not exist. Creating a new experiment.

<Experiment: artifact_location='s3://my-s3-bucket-of-store-artifact-youtube-data12/mlflow-artifacts/3', creation_time=1763800768169, experiment_id='3', last_update_time=1763800768169, lifecycle_stage='active', name='RF Baseline', tags={}>

In [15]:
X=df.iloc[:,1:]

In [17]:
y=df['sentiment_numeric']

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [20]:




# Split data into train/test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

#  Step 2: Define and train  a Random Forest baseline model using MLflow
with mlflow.start_run() as run:
    # --- MLflow Run Tags ---
    mlflow.set_tag("mlflow.runName", "RandomForest_Baseline_TrainTestSplit")
    mlflow.set_tag("experiment_type", "baseline")
    mlflow.set_tag("model_type", "RandomForestClassifier")
    mlflow.set_tag(
        "description",
        "Baseline RandomForest model for sentiment analysis  with a simple train-test split",
    )

    # --- Model Parameters ---
    n_estimators = 200
    max_depth = 15
    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)

    # --- Train Model ---
    model = RandomForestClassifier(
        n_estimators=n_estimators, max_depth=max_depth, random_state=42
    )
    model.fit(X_train, y_train)

    # --- Predictions ---
    y_pred = model.predict(X_test)

    # --- Metrics ---
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", accuracy)

    classification_rep = classification_report(y_test, y_pred, output_dict=True)
    for label, metrics in classification_rep.items():
        if isinstance(metrics, dict):  # Only log precision, recall, f1-score
            for metric, value in metrics.items():
                mlflow.log_metric(f"{label}_{metric}", value)

    # --- Confusion Matrix ---
    conf_matrix = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")

    # Save and log confusion matrix plot
    plt.savefig("confusion_matrix.png")
    mlflow.log_artifact("confusion_matrix.png")
    plt.close()

    # --- Log Model ---
    mlflow.sklearn.log_model(model, "random_forest_model")

    # --- Optionally Log Dataset (if small) ---
    # Example: if you have your DataFrame as df
    df.to_csv("dataset.csv", index=False)
    mlflow.log_artifact("dataset.csv")

# Print Final Accuracy
print(f" Accuracy: {accuracy:.4f}")

2025/11/22 14:18:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/11/22 14:19:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run RandomForest_Baseline_TrainTestSplit at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/3/runs/262defad41b74cc891cf698c37d73be1
🧪 View experiment at: http://ec2-51-20-104-217.eu-north-1.compute.amazonaws.com:5000/#/experiments/3
 Accuracy: 0.6403

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.61      0.38      0.47       862
           0       0.64      0.63      0.63      4546
           1       0.64      0.70      0.67      4488

    accuracy                           0.64      9896
   macro avg       0.63      0.57      0.59      9896
weighted avg       0.64      0.64      0.64      9896

In [48]:
df.to_csv('reddit_preprocessing.csv', index=False)

In [22]:
X

,word_count,num_stop_words,num_chars,num_punctuation_chars,category_gaming,category_movies,category_music,category_technology,hour,weekday,...,fear,anger,anticipation,trust,surprise,positive,negative,sadness,disgust,joy
0,24,9,116,1,0.0,0.0,0.0,1.0,19,5,...,0.0,0.0,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.333333
1,12,5,53,0,0.0,0.0,0.0,1.0,23,2,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
2,12,7,54,1,0.0,0.0,0.0,1.0,16,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
3,9,3,40,1,0.0,0.0,0.0,1.0,22,0,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000
4,15,6,85,4,0.0,0.0,0.0,1.0,12,0,...,0.0,0.0,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49472,6,0,30,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49473,7,0,34,1,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49474,8,0,45,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49475,7,1,38,0,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
49476,4,0,25,1,0.0,0.0,0.0,0.0,9,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000